// *scripts.js
   
    function openMainVideo(videoSrc) {
      var videoFrameContainer = document.getElementById('videoFrameContainer');
      var videoFrame = document.getElementById('videoFrame');
      videoFrame.src = videoSrc;
      videoFrameContainer.style.display = 'block';
    }

    function openLink(pdfFile) {
      var mainPDFFrameContainer = document.getElementById('mainPDFFrameContainer');
      var PDFFrame = document.getElementById('PDFFrame');
      PDFFrame.src = pdfFile;
      mainPDFFrameContainer.style.display = 'block';
    }

    function closeVideo() {
      var videoFrameContainer = document.getElementById('videoFrameContainer');
      var mainPDFFrameContainer = document.getElementById('mainPDFFrameContainer');
      videoFrameContainer.style.display = 'none';
      mainPDFFrameContainer.style.display = 'none';
      // Clear the src attribute to stop the video
      document.getElementById('videoFrame').src = '';
      document.getElementById('PDFFrame').src = '';
    }

    function watchVideo() {
      // Implement logic for watching the video
      alert('Watching the video...');
    }
  
    function closeIframe() {
      var iframeContainer = document.getElementById('videoFrameContainer');
      iframeContainer.style.display = 'none';
    }

    var originalIframeContent;
    
    function openIframeWindowIO() {
      // Store the content generated by openIframeWindowIO
      originalIframeContent = document.getElementById('mainContent').innerHTML;
      var iframeContainer = document.getElementById('customIframeContainer');
      var iframeContent = document.getElementById('customIframeContent');
  
      // Clear previous content
      iframeContent.innerHTML = '';
  
      // Create container for 1st of two boxes
      var boxContainer = document.createElement('div');
      boxContainer.className = 'customBoxContainer';

      // Create container for 2nd of two boxes
      var secondboxContainer = document.createElement('div');
      secondboxContainer.className = 'secondBoxContainer';

      // Create container for 3rd of two boxes
      var thirdboxContainer = document.createElement('div');
      thirdboxContainer.className = 'thirdBoxContainer';
  
      // Create left box
      var leftBox = document.createElement('div');
      leftBox.className = 'customBox';
      createCustomBox(leftBox, 'images/TeamsLikeLayout.png', 'Play Video', 'Open PDF', 'Teams Like Layout');
      boxContainer.appendChild(leftBox);

      // Create second left box underneath
      var secondLeftBox = document.createElement('div');
      secondLeftBox.className = 'secondBox';
      createCustomBox(secondLeftBox, 'images/TeamsActiveSpeaker.png', 'Play Video', 'Open PDF', 'Teams Active Speaker');
      secondboxContainer.appendChild(secondLeftBox);

      // Create third left box underneath
      var thirdLeftBox = document.createElement('div');
      thirdLeftBox.className = 'thirdBox';
      createCustomBox(thirdLeftBox, 'images/MS_P2P.png', 'Play Video', 'Open PDF', 'Microsoft Direct 1:1 calling (MTR)');
      thirdboxContainer.appendChild(thirdLeftBox);
  
      // Create right box
      var rightBox = document.createElement('div');
      rightBox.className = 'customBox';
      createCustomBox(rightBox, 'images/TeamsRaisedHand.png', 'Play Video', 'Open PDF', 'Teams Like Layout Raised Hand');
      boxContainer.appendChild(rightBox);

      // Create second right box underneath
      var secondRightBox = document.createElement('div');
      secondRightBox.className = 'secondBox';
      createCustomBox(secondRightBox, 'images/TeamsSpotlight.png', 'Play Video', 'Open PDF', 'Teams Spot Light');
      secondboxContainer.appendChild(secondRightBox);

      // Create third right box underneath
      var thirdRightBox = document.createElement('div');
      thirdRightBox.className = 'thirdBox';
      createCustomBox(thirdRightBox, 'images/MS_SGJ.png', 'Play Video', 'Open PDF', 'Microsoft SIP Guest Join');
      thirdboxContainer.appendChild(thirdRightBox);
  
      // Append box container to the iframe content
      iframeContent.appendChild(boxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(secondboxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(thirdboxContainer);

      // Set overflow property for iframeContent to make it scrollable
      iframeContent.style.overflow = 'auto';
       
      // Add event listeners to the buttons
      leftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_AI-technology.mp4');
      });

      leftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      secondLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      secondLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      thirdLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Point2Point.mp4');
      });

      thirdLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      rightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_raised-hand.mp4');
      });

      rightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      secondRightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_Spotlighting.mp4');
      });

      secondRightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      thirdRightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/SIPGuestJoin.mp4');
      });

      thirdRightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

   function createCustomBox(container, imageUrl, button1Text, button2Text, description) {
      var image = document.createElement('img');
      image.src = imageUrl;
  
      var paragraph = document.createElement('p');
      paragraph.textContent = description;
  
      var button1 = document.createElement('button');
      button1.textContent = button1Text;
      button1.className = 'customButton1'; // Add a class for identification
      button1.onclick = function() {
        // Button 1 click handled in the event listener
      };
  
      var button2 = document.createElement('button');
      button2.textContent = button2Text;
      button2.className = 'customButton2'; // Add a class for identification
      button2.onclick = function() {
        // Button 2 click handled in the event listener
      };
  
      // Append elements to the container
      container.appendChild(image);
      container.appendChild(paragraph);
      container.appendChild(button1);
      container.appendChild(button2);
    }
      
      // Display the iframe container
      iframeContainer.style.display = 'block';
    }

    function openIframeWindowHC() {
      // Store the content generated by openIframeWindowHC
      originalIframeContent = document.getElementById('mainContent').innerHTML;
      var iframeContainer = document.getElementById('customIframeContainer');
      var iframeContent = document.getElementById('customIframeContent');
  
      // Clear previous content
      iframeContent.innerHTML = '';
  
      // Create container for two boxes
      var boxContainer = document.createElement('div');
      boxContainer.className = 'customBoxContainer';

      // Create container for 2nd of two boxes
      var secondboxContainer = document.createElement('div');
      secondboxContainer.className = 'secondBoxContainer';

      // Create container for 3nd of two boxes
      var thirdboxContainer = document.createElement('div');
      thirdboxContainer.className = 'thirdBoxContainer';

      // Create container for 4th of two boxes
      var fourthboxContainer = document.createElement('div');
      fourthboxContainer.className = 'fourthBoxContainer';
  
      // Create left box
      var leftBox = document.createElement('div');
      leftBox.className = 'customBox';
      createCustomHCBox(leftBox, 'images/realwear.png', 'Play Video', 'QR Code', 'Headset Window Screenshots', 'RealWear HMT-1 on Pexip Infinity');
      boxContainer.appendChild(leftBox);

      // Create second left box underneath
      var secondLeftBox = document.createElement('div');
      secondLeftBox.className = 'secondBox';
      createCustomHCBox(secondLeftBox, 'images/plugins.png', 'Play Video', 'Open PDF', 'Interactive Demo (2 Windows)', 'WebApp2 Plugins');
      secondboxContainer.appendChild(secondLeftBox);

      // Create third left box underneath
      var thirdLeftBox = document.createElement('div');
      thirdLeftBox.className = 'thirdBox';
      createCustomHCBox(thirdLeftBox, 'images/playbackVMR.png', 'Play Video', 'Open PDF', 'Interactive Demo', 'Video Playback Before Session');
      thirdboxContainer.appendChild(thirdLeftBox);

      // Create fourth left box underneath
      var fourthLeftBox = document.createElement('div');
      fourthLeftBox.className = 'fourthBox';
      createCustomHCBox(fourthLeftBox, 'images/dashboard.png', 'Play Video', 'Open PDF', 'Interactive Demo', 'Custom Dashboard - MGT API');
      fourthboxContainer.appendChild(fourthLeftBox);
       
      // Create right box
      var rightBox = document.createElement('div');
      rightBox.className = 'customBox';
      createCustomHCBox(rightBox, 'images/breakoutrooms.png', 'Play Video', 'Open PDF', 'Interactive Demo (3 Windows)', 'Breakout Rooms');
      boxContainer.appendChild(rightBox);

      // Create second right box underneath
      var secondRightBox = document.createElement('div');
      secondRightBox.className = 'secondBox';
      createCustomHCBox(secondRightBox, 'images/hospitalmap.png', 'Play Video', 'Open PDF', 'Interactive Demo (2 Windows)', 'Rounding Map');
      secondboxContainer.appendChild(secondRightBox);

      // Create third right box underneath
      var thirdRightBox = document.createElement('div');
      thirdRightBox.className = 'thirdBox';
      createCustomHCBox(thirdRightBox, 'images/pexCaptioning.png', 'Play Video', 'Open PDF', 'Interactive Demo', 'Captioning');
      thirdboxContainer.appendChild(thirdRightBox);
  
      // Append box container to the iframe content
      iframeContent.appendChild(boxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(secondboxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(thirdboxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(fourthboxContainer);

      // Set overflow property for iframeContent to make it scrollable
      iframeContent.style.overflow = 'auto';

      // Add event listeners to the buttons
      leftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/rwVideo.mp4');
      });

      leftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPNG('images/qr-code.png');
      });

      leftBox.querySelector('.customButton3').addEventListener('click', function() {
        openPNG('images/rwHeadsetScreen.png');
      });

      // Add event listeners to the buttons
      secondLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      secondLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/customizingPexip.pdf');
      });

      // Add a new event listener for customButton3
      secondLeftBox.querySelector('.customButton3').addEventListener('click', function() {
        // Open the first HTML link on the left side
        open2WinHTML('https://cklab-edges.ck-collab-engtest.com/Webapp2_Custom-pHealth/conference/ph1029?callType=video&muteMicrophone=true&muteCamera=true&name=Provider&role=host&pin=2023', 'left');
      
        // Open the second HTML link on the left side
        open2WinHTML('https://cklab-edges.ck-collab-engtest.com/Webapp2_Custom-pHealth/conference/ph1029?callType=video&name=Patient&role=guest', 'right');
      });

      // Add event listeners to the buttons
      thirdLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      thirdLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add a new event listener for customButton3
      thirdLeftBox.querySelector('.customButton3').addEventListener('click', function() {
        // Open the first HTML link on the left side
        open1WinHTML('https://cklab-edges.ck-collab-engtest.com/webapp3/step-by-step?name=Patient&conference=countdown&role=guest', 'left');
      });

      // Add event listeners to the buttons
      fourthLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      fourthLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/CustomDashboards.pdf');
      });
       
      // Add a new event listener for customButton3
      fourthLeftBox.querySelector('.customButton3').addEventListener('click', function() {
        // Open the first HTML link on the left side
        open1WinHTML('https://app.powerbi.com/groups/me/reports/3b8aa0a8-57c0-4d5f-8349-93cb8071ac78/ReportSectioncd6f5a0baa0a0ceddc59?experience=power-bi', 'left');
      });
       
      // Add event listeners to the buttons
      rightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_raised-hand.mp4');
      });

      rightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/BreakoutRooms.pdf');
      });

      // Add a new event listener for customButton3
      rightBox.querySelector('.customButton3').addEventListener('click', function() {
          // Open the first window on the left side
          const windowLeft = window.open('https://cklab-edges.ck-collab-engtest.com/webapp3/?name=Clinician%20Demo%20User&conference=genbreakoutrooms&role=host&pin=2023', '_blank', 'width=800,height=600,top=100,left=100');
      
          // Open the second window in the middle
          const windowMiddle = window.open('https://cklab-edges.ck-collab-engtest.com/webapp3/step-by-step?name=Patient%20One&conference=genbreakoutrooms&role=guest', '_blank', 'width=800,height=600,top=100,left=500');
      
          // Open the third window on the right side
          const windowRight = window.open('https://cklab-edges.ck-collab-engtest.com/webapp3/?name=Patient%20Two&conference=genbreakoutrooms&role=guest&callType=video&join=1', '_blank', 'width=800,height=600,top=100,left=900');
      });

      // Add event listeners to the buttons
      secondRightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      secondRightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/rounding.pdf');
      });

      // Add a new event listener for customButton3
      secondRightBox.querySelector('.customButton3').addEventListener('click', function() {
        // Open the first HTML link on the left side
        open2WinHTML('https://ckeilberg57.github.io/ManuMap/', 'left');
      
        // Open the second HTML link on the right side
        open2WinHTML('https://ckeilberg57.github.io/mockcart', 'right');
      });

      // Add a new event listener for customButton3
      thirdRightBox.querySelector('.customButton3').addEventListener('click', function() {
        // Open the first HTML link on the left side
        open1WinHTML('https://pex-gcc.com/webapp3/express?name=Provider&conference=drdemo&role=host&pin=2023', 'left');
      });

      // Display the iframe container
      iframeContainer.style.display = 'block';
    }

    function createCustomHCBox(container, imageUrl, button1Text, button2Text, button3Text, description) {
      var image = document.createElement('img');
      image.src = imageUrl;
  
      var paragraph = document.createElement('p');
      paragraph.textContent = description;
  
      var button1 = document.createElement('button');
      button1.textContent = button1Text;
      button1.className = 'customButton1'; // Add a class for identification
      button1.onclick = function() {
        // Button 1 click handled in the event listener
      };
  
      var button2 = document.createElement('button');
      button2.textContent = button2Text;
      button2.className = 'customButton2'; // Add a class for identification
      button2.onclick = function() {
        // Button 2 click handled in the event listener
      };

      var button3 = document.createElement('button');
      button3.textContent = button3Text;
      button3.className = 'customButton3'; // Add a class for identification
      button3.onclick = function() {
        // Button 3 click handled in the event listener
      };
  
      // Append elements to the container
      container.appendChild(image);
      container.appendChild(paragraph);
      container.appendChild(button1);
      container.appendChild(button2);
      container.appendChild(button3);
    }

      function openVideo(videoSrc) {
      var iframeContent = document.getElementById('customIframeContent');
      iframeContent.innerHTML = `<iframe id="videoFrame" width="100%" height="100%" src="${videoSrc}" frameborder="0" allowfullscreen></iframe>`;
    }

      function openPDF(pdfFile) {
      // Update the iframeContent to display the PDF
      var iframeContent = document.getElementById('customIframeContent');
      iframeContent.innerHTML = `<iframe id="pdfFrame" width="100%" height="100%" src="${pdfFile}" frameborder="0" allowfullscreen></iframe>`;
    }

      function openPNG(pngFile) {
        // Update the iframeContent to display the PNG with a white box
        var iframeContent = document.getElementById('customIframeContent');
        iframeContent.innerHTML = `
          <div style="border: 2px solid white; padding: 10px; display: inline-block;">
            <img src="${pngFile}" alt="QR Code" style="width: 100%; height: auto;">
          </div>
        `;
      }

      function open1WinHTML(url) {
        // Calculate the width of the window based on the screen width
        var windowWidth = Math.floor(screen.width);
      
        // Open the window with the specified URL, width, height, and position
        window.open(url, 'singleWindow', 'width=' + windowWidth + ',height=' + screen.height + ',top=0,left=0');
      }

       function open2WinHTML(url, side) {
         // Calculate the width of each window based on the screen width
         var windowWidth = Math.floor(screen.width / 2);
   
         // Calculate the left position based on the side parameter
         var leftPosition = (side === 'left') ? 0 : windowWidth;
   
         // Open the window with the specified URL, width, height, and position
         window.open(url, side + 'Window', 'width=' + windowWidth + ',height=' + screen.height + ',top=0,left=' + leftPosition);
       }

        function open3WinHTML(url1, url2, side) {
          // Calculate the width of each window based on the screen width
          var windowWidth = Math.floor(screen.width / 2);
      
          // Calculate the left position based on the side parameter
          var leftPosition = (side === 'left') ? 0 : windowWidth;
      
          // Open the window with the specified URL, width, height, and position
          var newWindow = window.open(url1, side + 'Window', 'width=' + windowWidth + ',height=' + screen.height + ',top=0,left=' + leftPosition);
      
          // If it's the right window, open the second HTML link in a new tab
          if (side === 'right') {
            newWindow.open(url2, '_blank');
          }
        }

       function closeIframeWindow() {
         var iframeContainer = document.getElementById('customIframeContainer');
         var iframeContent = document.getElementById('customIframeContent');
     
         // Restore the initial state of openIframeWindowIO
         iframeContent.innerHTML = originalIframeContent;
     
         // Clear the content inside customIframeContent
         iframeContent.innerHTML = '';
     
         // Hide the custom iframe container
         iframeContainer.style.display = 'none';
       }
