// *scripts.js
   
    function openMainVideo(videoSrc) {
      var videoFrameContainer = document.getElementById('videoFrameContainer');
      var videoFrame = document.getElementById('videoFrame');
      videoFrame.src = videoSrc;
      videoFrameContainer.style.display = 'block';
    }

    function openLink(pdfFile) {
      var mainPDFFrameContainer = document.getElementById('mainPDFFrameContainer');
      var PDFFrame = document.getElementById('PDFFrame');
      PDFFrame.src = pdfFile;
      mainPDFFrameContainer.style.display = 'block';
    }

    function closeVideo() {
      var videoFrameContainer = document.getElementById('videoFrameContainer');
      var mainPDFFrameContainer = document.getElementById('mainPDFFrameContainer');
      videoFrameContainer.style.display = 'none';
      mainPDFFrameContainer.style.display = 'none';
      // Clear the src attribute to stop the video
      document.getElementById('videoFrame').src = '';
      document.getElementById('PDFFrame').src = '';
    }

    function watchVideo() {
      // Implement logic for watching the video
      alert('Watching the video...');
    }
  
    function closeIframe() {
      var iframeContainer = document.getElementById('videoFrameContainer');
      iframeContainer.style.display = 'none';
    }

    var originalIframeContent;
    
    function openIframeWindowIO() {
      // Store the content generated by openIframeWindowIO
      originalIframeContent = document.getElementById('mainContent').innerHTML;
      var iframeContainer = document.getElementById('customIframeContainer');
      var iframeContent = document.getElementById('customIframeContent');
  
      // Clear previous content
      iframeContent.innerHTML = '';
  
      // Create container for 1st of two boxes
      var boxContainer = document.createElement('div');
      boxContainer.className = 'customBoxContainer';

      // Create container for 2nd of two boxes
      var secondboxContainer = document.createElement('div');
      secondboxContainer.className = 'secondBoxContainer';
  
      // Create left box
      var leftBox = document.createElement('div');
      leftBox.className = 'customBox';
      createCustomBox(leftBox, 'images/TeamsLikeLayout.png', 'Play Video', 'Open PDF', 'Teams Like Layout');
      boxContainer.appendChild(leftBox);

      // Create second left box underneath
      var secondLeftBox = document.createElement('div');
      secondLeftBox.className = 'secondBox';
      createCustomBox(secondLeftBox, 'images/TeamsActiveSpeaker.png', 'Play Video', 'Open PDF', 'Teams Active Speaker');
      secondboxContainer.appendChild(secondLeftBox);
  
      // Create right box
      var rightBox = document.createElement('div');
      rightBox.className = 'customBox';
      createCustomBox(rightBox, 'images/TeamsRaisedHand.png', 'Play Video', 'Open PDF', 'Teams Like Layout Raised Hand');
      boxContainer.appendChild(rightBox);

      // Create second right box underneath
      var secondRightBox = document.createElement('div');
      secondRightBox.className = 'secondBox';
      createCustomBox(secondRightBox, 'images/TeamsSpotlight.png', 'Play Video', 'Open PDF', 'Teams Spot Light');
      secondboxContainer.appendChild(secondRightBox);
  
      // Append box container to the iframe content
      iframeContent.appendChild(boxContainer);

      // Append box container to the iframe content
      iframeContent.appendChild(secondboxContainer);
       
      // Add event listeners to the buttons
      leftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_AI-technology.mp4');
      });

      leftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      secondLeftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_active-speaker.mp4');
      });

      secondLeftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      rightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_raised-hand.mp4');
      });

      rightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

      // Add event listeners to the buttons
      secondRightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_Spotlighting.mp4');
      });

      secondRightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });

   function createCustomBox(container, imageUrl, button1Text, button2Text, description) {
      var image = document.createElement('img');
      image.src = imageUrl;
  
      var paragraph = document.createElement('p');
      paragraph.textContent = description;
  
      var button1 = document.createElement('button');
      button1.textContent = button1Text;
      button1.className = 'customButton1'; // Add a class for identification
      button1.onclick = function() {
        // Button 1 click handled in the event listener
      };
  
      var button2 = document.createElement('button');
      button2.textContent = button2Text;
      button2.className = 'customButton2'; // Add a class for identification
      button2.onclick = function() {
        // Button 2 click handled in the event listener
      };
  
      // Append elements to the container
      container.appendChild(image);
      container.appendChild(paragraph);
      container.appendChild(button1);
      container.appendChild(button2);
    }
      
      // Display the iframe container
      iframeContainer.style.display = 'block';
    }

    function openIframeWindowHC() {
      // Store the content generated by openIframeWindowHC
      originalIframeContent = document.getElementById('mainContent').innerHTML;
      var iframeContainer = document.getElementById('customIframeContainer');
      var iframeContent = document.getElementById('customIframeContent');
  
      // Clear previous content
      iframeContent.innerHTML = '';
  
      // Create container for two boxes
      var boxContainer = document.createElement('div');
      boxContainer.className = 'customBoxContainer';
  
      // Create left box
      var leftBox = document.createElement('div');
      leftBox.className = 'customBox';
      createCustomHCBox(leftBox, 'images/realwear.png', 'Play Video', 'QR Code', 'Headset Window Screenshots', 'RealWear HMT-1 on Pexip Infinity');
      boxContainer.appendChild(leftBox);
  
      // Create right box
      var rightBox = document.createElement('div');
      rightBox.className = 'customBox';
      createCustomHCBox(rightBox, 'images/breakoutrooms.png', 'Play Video', 'Open PDF', 'Interactive Demo', 'Breakout Rooms');
      boxContainer.appendChild(rightBox);
  
      // Append box container to the iframe content
      iframeContent.appendChild(boxContainer);

      // Add event listeners to the buttons
      leftBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/rwVideo.mp4');
      });

      leftBox.querySelector('.customButton2').addEventListener('click', function() {
        openPNG('images/qr-code.png');
      });

      leftBox.querySelector('.customButton3').addEventListener('click', function() {
        openPNG('images/rwHeadsetScreen.png');
      });

      // Add event listeners to the buttons
      rightBox.querySelector('.customButton1').addEventListener('click', function() {
        openVideo('videos/Teams-like_raised-hand.mp4');
      });

      rightBox.querySelector('.customButton2').addEventListener('click', function() {
        openPDF('PPs/TeamsLikeLayout.pdf');
      });
      
      // Display the iframe container
      iframeContainer.style.display = 'block';
    }
  
    function createCustomHCBox(container, imageUrl, button1Text, button2Text, button3Text, description) {
      var image = document.createElement('img');
      image.src = imageUrl;
  
      var paragraph = document.createElement('p');
      paragraph.textContent = description;
  
      var button1 = document.createElement('button');
      button1.textContent = button1Text;
      button1.className = 'customButton1'; // Add a class for identification
      button1.onclick = function() {
        // Button 1 click handled in the event listener
      };
  
      var button2 = document.createElement('button');
      button2.textContent = button2Text;
      button2.className = 'customButton2'; // Add a class for identification
      button2.onclick = function() {
        // Button 2 click handled in the event listener
      };

      var button3 = document.createElement('button');
      button3.textContent = button3Text;
      button3.className = 'customButton3'; // Add a class for identification
      button3.onclick = function() {
        // Button 3 click handled in the event listener
      };
  
      // Append elements to the container
      container.appendChild(image);
      container.appendChild(paragraph);
      container.appendChild(button1);
      container.appendChild(button2);
      container.appendChild(button3);
    }

      function openVideo(videoSrc) {
      var iframeContent = document.getElementById('customIframeContent');
      iframeContent.innerHTML = `<iframe id="videoFrame" width="100%" height="100%" src="${videoSrc}" frameborder="0" allowfullscreen></iframe>`;
    }

      function openPDF(pdfFile) {
      // Update the iframeContent to display the PDF
      var iframeContent = document.getElementById('customIframeContent');
      iframeContent.innerHTML = `<iframe id="pdfFrame" width="100%" height="100%" src="${pdfFile}" frameborder="0" allowfullscreen></iframe>`;
    }

      function openPNG(pngFile) {
        // Update the iframeContent to display the PNG with a white box
        var iframeContent = document.getElementById('customIframeContent');
        iframeContent.innerHTML = `
          <div style="border: 2px solid white; padding: 10px; display: inline-block;">
            <img src="${pngFile}" alt="QR Code" style="width: 100%; height: auto;">
          </div>
        `;
      }

       function closeIframeWindow() {
         var iframeContainer = document.getElementById('customIframeContainer');
         var iframeContent = document.getElementById('customIframeContent');
     
         // Restore the initial state of openIframeWindowIO
         iframeContent.innerHTML = originalIframeContent;
     
         // Clear the content inside customIframeContent
         iframeContent.innerHTML = '';
     
         // Hide the custom iframe container
         iframeContainer.style.display = 'none';
       }

